### ISSUE TITLE
Exception caught by animation library

### ISSUE THREAD

**Issue by abhlabs** [edasandesu/flutter_image_slideshow#1]
I'm getting this error when I swipe my images.  Using version 0.0.2+2, Dart 2.10.4, Flutter 1.22.4.
`
════════ Exception caught by animation library ═════════════════════════════════
The method 'call' was called on null.
Receiver: null
Tried calling: call()`

**Comment by edasandesu** [comment]
@abhlabs 
Thank you for teaching me! 
I fixed this issue. You can try it on master branch.
