### ISSUE TITLE
Widget test failed

### ISSUE THREAD

**Issue by kenho85** [edasandesu/flutter_image_slideshow#14]
the package is fine; however, when I write a widget case to cover it, it will fail automatically. I am guessing the reason is caused by the Timer in ur package. I guess u disposed the widget without freeing the timer. Please correct me if I am wrong. 

Pending timers:
Timer (duration: 0:00:04.000000, periodic: true), created:
#0      new FakeTimer._ (package:fake_async/fake_async.dart:308:62)
#1      FakeAsync._createTimer (package:fake_async/fake_async.dart:252:27)
#2      FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:187:19)
#5      ImageSlideshowState._autoPlayTimerStart (package:flutter_image_slideshow/src/image_slideshow.dart:75:20)
#6      ImageSlideshowState.initState (package:flutter_image_slideshow/src/image_slideshow.dart:117:7)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5015:57)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
...     Normal element mounting (16 frames)
#24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#25     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#26     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447:32)
...     Normal element mounting (111 frames)
#137    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#138    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#139    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447:32)
...     Normal element mounting (117 frames)
#256    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#257    Element.updateChild (package:flutter/src/widgets/framework.dart:3586:20)
#258    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1195:16)
#259    RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1172:5)
#260    RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1186:7)
#261    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#262    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#263    AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1191:19)
#264    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#265    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#266    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#267    AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1057:9)
#270    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#271    AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1043:27)
#272    WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:554:22)
#275    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#276    WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:551:27)
#277    main.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/kenimac/Desktop/seeker-mobile/test/ui/pages/home/HomeBanner_test.dart:21:47)
#282    HttpOverrides.runZoned (dart:_http/overrides.dart:57:26)
#283    mockNetworkImagesFor (package:network_image_mock/src/network_image_mock.dart:9:24)
#284    main.<anonymous closure>.<anonymous closure> (file:///Users/kenimac/Desktop/seeker-mobile/test/ui/pages/home/HomeBanner_test.dart:21:13)
#285    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 11 frames from dart:async and package:stack_trace)

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
A Timer is still pending even after the widget tree was disposed.
'package:flutter_test/src/binding.dart':
Failed assertion: line 1299 pos 12: '!timersPending'

**Comment by edasandesu** [comment]
@kenho85 
Thank you for letting me know!
I had forgotten to dispose of the Timer.
I will fix it.

**Comment by edasandesu** [comment]
I published.
