### ISSUE TITLE
Enhancement request: AutoAdvance

### ISSUE THREAD

**Issue by abhlabs** [edasandesu/flutter_image_slideshow#2]
Add an "AutoAdvance" (or maybe "AutoPlay") feature so user doesn't have to swipe the screen to view all the slides.  Something like this might work:

```
autoAdvanceInterval:  3000;   // in milliseconds.  Set to zero to disable AutoAdvance
endOfListBehavior:  loop;     // "loop" to return to first slide, or "stop" to stop advancing
```
Any taps on the slide would pause the autoAdvance and swipes would resume it.

**Comment by edasandesu** [comment]
@abhlabs 
Thank you for your request.
I will try to develop AutoAdvance

**Comment by edasandesu** [comment]
Added only "AutoPlay" feature.
It will loop at the end of the slide.

**Comment by abhlabs** [comment]
My apologies for not getting back here to thank you for implementing this feature.

Do you think it might be possible to change the way package loops back to slide #1?  Instead of showing all the slides quickly in reverse order, could you make it go directly from slide "N" back to  slide #1 in such a way that it appears to be slide "N+1"?

**Comment by edasandesu** [comment]
@abhlabs 
Changed the way loops back to first slide, and Added "isLoop" variable.
Please, try it!

**Comment by abhlabs** [comment]
> Changed the way loops back to first slide, and Added "isLoop" variable. Please, try it!

Looks great, thanks!
