### ISSUE TITLE
Unhandled exception scroll controller

### ISSUE THREAD

**Issue by UmairRehmat** [edasandesu/flutter_image_slideshow#3]
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 108 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
E/flutter (18004): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (18004): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (18004): #2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:108:12)
E/flutter (18004): #3      PageController.animateToPage (package:flutter/src/widgets/page_view.dart:193:41)
E/flutter (18004): #4      _ImageSlideshowState.initState.<anonymous closure> (package:flutter_image_slideshow/flutter_image_slideshow.dart:113:27)

**Comment by edasandesu** [comment]
@UmairRehmat 
Without more information, I will not be able to resolve this issue.
Can you provide a runnable reproduction of this issue so I can better find out what the cause may be?
Thank you!

**Comment by UmairRehmat** [comment]
i set the slider in bottom navigation and when i change the view it shows this error. What i understand is there should be a controller sent through parameter so i could strict to the view

**Comment by edasandesu** [comment]
@UmairRehmat 
Thank you for teaching me!
I added processing to check clients before animateToPage.
Please, try it.

**Comment by UmairRehmat** [comment]
It’s s handled. great 👍
