### ISSUE TITLE
Full width to image slider does not work

### ISSUE THREAD

**Issue by UmairSaqibBhutta** [edasandesu/flutter_image_slideshow#7]
Below is my code where I am assigning full width to image slider but it does not work
` ImageSlideshow(
              initialPage: 0,
              height: getHeight(context) * .3,
              width: getWidth(context),
              // autoPlayInterval: 1,
              // isLoop: true,
              children: data.images!
                  .map((image) => Image(image: NetworkImage(image.image)))
                  .toList(),
            ),`

**Comment by UmairSaqibBhutta** [comment]
in below code, getHeight() and getWidth() are methods for getting full height and width. Use any image for testing.

`    ImageSlideshow(
              initialPage: 0,
              height: getHeight(context) * .3,
              width: getWidth(context),
              children: data.images!
                  .map((image) => Image(image: NetworkImage(image.image)))
                  .toList(),
            ),`

**Comment by edasandesu** [comment]
@UmairSaqibBhutta 
Hmm... I don't know.

See an example of my packages.
[example/main.dart](https://github.com/edasandesu/flutter_image_slideshow/blob/c717decf1a25704d47239cad3ac9ab4204af765c/example/main.dart#L17)
It does work, full width(double.infinity).
I also tried full height but it worked.

Can you provide a runnable reproduction of this issue?
(like the whole code or whole widget)
